### ISSUE TITLE
Developers: Requested Rippers up-for-grabs (meta-issue)

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#43]
<a href="https://github.com/metaprime"><img src="https://avatars1.githubusercontent.com/u/7526632?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [metaprime](https://github.com/metaprime)**
_Tuesday Apr 25, 2017 at 07:45 GMT_
_Originally opened as https://github.com/4pr0n/ripme/issues/510_

----

# Note: assume all links are NSFW

If you would like to develop a ripper which has been requested, please open an issue (to function as a work item) indicating that you've claimed a ripper and you're working on an implementation. Please link back to this issue (and 4pr0n#502 as an FYI) so that GitHub makes a link to the issue (work item) appear in this thread and 4pr0n#502.

~~I'm locking this conversation to ensure requests and general comments stay on 4pr0n#502.~~ (It looks like link-backs won't appear on a locked issue, so I won't be able to lock this issue.)

To keep this issue focused, **I will delete requests and non-dev-related comments (please use 4pr0n#502 for these).**

Below is a list of rippers and functionality requested via 4pr0n#502 and 4pr0n#8 (this list is a work in progress -- I'm posting a thumbs-up reaction on any requests I have added to this list). Please assume all links are NSFW.

### High priority (existing rippers: broken or missing functionality)

* [ ] Fix `DeviantART`: 4pr0n#272 4pr0n#112 4pr0n#63
* [ ] `DeviantART` favorites galleries e.g. http://philosophyfetish.deviantart.com/favourites/ ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-296430431))
* [ ] `DeviantART` gallery recursive ripping (4pr0n#550)
* [ ] `Tumblr` liked by {User}: https://www.tumblr.com/liked/by/hacky-gif ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-296959726))
* [ ] `eroshare` User Pages (4pr0n#465) and direct links (4pr0n#526)

### Everything else:

* [ ] `PurplePort`: https://purpleport.com/ e.g. https://purpleport.com/portfolio/bluethealienteafairy/ ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-292073508))
* [ ] `CFake`: http://cfake.com/ e.g. http://cfake.com/picture/Olivia-Munn/969 ([Request](https://github.com/4pr0n/ripme/issues/8#issuecomment-163521926), [Comment](https://github.com/4pr0n/ripme/issues/8#issuecomment-286962054), [Comment](https://github.com/4pr0n/ripme/issues/502#issuecomment-292816317))
* [ ] `VSCO`: http://www.vsco.co e.g. https://vsco.co/lukept/images/1 ([Request](https://github.com/4pr0n/ripme/issues/8#issuecomment-284197479), [Comment](https://github.com/4pr0n/ripme/issues/8#issuecomment-290597282), [Comment](https://github.com/4pr0n/ripme/issues/502#issuecomment-292129058))
* [ ] `zenfolio` https://en.zenfolio.com ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-293748612))
* [ ] `smugmug` https://www.smugmug.com/ ([Request](https://github.com/4pr0n/ripme/issues/502#issuecomment-293748612))
* [ ] `sex.com`: (Request: https://github.com/4pr0n/ripme/issues/274)
* [ ] `vidble.com`: video links https://www.vidble.com/watch?v=i82m7v88HHTl82DwgEfbZHQ7ySchrUZd [Request](https://github.com/RipMeApp/ripme/issues/38#issuecomment-337753614)
* [ ] `imageshack.com`: https://imageshack.com/a/vsWl/1 [Request](https://github.com/RipMeApp/ripme/issues/38#issuecomment-341919784)

### Pending sites + examples (from 4pr0n#8)

- `getgonewild` - http://www.getgonewild.com/profile/rollmeup
- `blogspot` - http://marcherryfashion.blogspot.com/
- `pixiv` - http://www.pixiv.net/member.php?id=2136123
- `facebook` - https://www.facebook.com/EmanueleFerrariPhotographer/photos_stream
- `pinterest` - http://www.pinterest.com/
- `lookbook` - http://lookbook.nu/mayowo
- `4shared` - http://www.4shared.com/folder/pTUpT6wG/Heather.html
- `behance` - https://www.behance.net/HS-nj
- `dribbble` - https://dribbble.com/studioMUTI
- `fetlife` - https://fetlife.com/users/2089769
- `diverxity` - http://www.diverxity.com/users/953
- `studio-g` - http://studio-g.tistory.com/535
- `fg-site` - http://www.fg-site.net/members/umeume/
- `gelbooru` - http://gelbooru.com/index.php?page=post&s=list&tags=futa
- `thefappening.sexy` - http://thefappening.sexy/albums/index.php?/category/126
- `ipernity` - http://www.ipernity.com/doc/kimcums/album/676241
- `punterplanet` - http://guide.punterplanet.com/escorts/featured/frontpage/amber-green_200.html
- `rule34` - rule34.paheal.net
- `photoblog.pl` - http://www.photoblog.pl/colordust/170020651/typical-girl.html
- `megamodels.pl` - http://www.megamodels.pl/a-ya
- `maxmodels.pl` - http://www.maxmodels.pl/modelka-agnes-z-garbledville.html
- `flog.pl` - http://www.flog.pl/szukaj/akt

### Enhancement requests (list from 4pr0n#8):

- `flickr` - login support (see 4pr0n#32)
- `vk` - Video ripper rename files (https://github.com/4pr0n/ripme/issues/8#issuecomment-41349715)
- `twitter` - Search ripping (https://github.com/4pr0n/ripme/issues/8#issuecomment-41471274)
- `gifyo` - Don't skip some images
- `*chan rippers` - Handle external links (vocaroo), store comments
- `tumblr` - Rip by date (`/archive/year/month`) (https://github.com/4pr0n/ripme/issues/8#issuecomment-41395317)

### Acknowledged but defunct requests:

* ~~kinkyshare.com (now redirects to sex.com, old content seems to be gone) ([Request](https://github.com/4pr0n/ripme/issues/8#issuecomment-40618854))~~
* ~~`artician` - http://zionenciel.artician.com/~~

**Comment by metaprime** [comment]
<a href="https://github.com/Wiiplay123"><img src="https://avatars2.githubusercontent.com/u/9746793?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Wiiplay123](https://github.com/Wiiplay123)**
_Wednesday Apr 26, 2017 at 02:32 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

I've made a working implementation to fix deviantArt ripping and submitted a pull request, but I think it could be done better when someone has the time if they use org.json. Should I still make an issue even if I'm not likely to be able to  continue to devote much time to it?

**Comment by metaprime** [comment]
<a href="https://github.com/metaprime"><img src="https://avatars1.githubusercontent.com/u/7526632?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [metaprime](https://github.com/metaprime)**
_Tuesday May 09, 2017 at 10:11 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

@Wiiplay123 I think there are plenty of issues already open to track the various DeviantArt problems. If you have a patch, please open a PR. If you don't think it's good enough, it won't work, or whatever, please make that clear in the pull request description. Maybe someone else will be able to pick up the work.

**Comment by metaprime** [comment]
<a href="https://github.com/Wiiplay123"><img src="https://avatars2.githubusercontent.com/u/9746793?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Wiiplay123](https://github.com/Wiiplay123)**
_Tuesday May 09, 2017 at 15:31 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

I opened a PR, turns out the modified ripper is even better than the original ripper, since it accounts for those annoying download redirects that redirect you back to the gallery page.

**Comment by cyian-1756** [comment]
> direct links

Shouldn't direct links get their own ripper rather than be implemented per site?

**Comment by rautamiekka** [comment]
What is the problem with https://github.com/4pr0n/ripme/issues/272 ? It's just an ignorant User being clueless (no offence meant), and the ability to open archives is absolutely not dependent on the target site.

**Comment by rautamiekka** [comment]
Replied to https://github.com/4pr0n/ripme/issues/112

**Comment by rautamiekka** [comment]
Replied/linked to https://github.com/4pr0n/ripme/issues/63

**Comment by metaprime** [comment]
@cyian-1756 Good point. I think that should be true in general. But making the triggers play nicely with each other is another story. As long as we can detect a URL with an extension that indicates the filetype, you'd expect it to be doable. But web servers can do whatever they want and you get a lot of sites that have blahblah.com/gallery/image.jpg and that page is actually a text/html MIME type with an `<img>` tag for the real image. So, for some sites, it would need to be implemented separately.

**Comment by metaprime** [comment]
> the ability to open archives is absolutely not dependent on the target site

@rautamiekka you make a good point -- I've closed 4pr0n/ripme#272

**Comment by metaprime** [comment]
I'm planning to take bobx.com when I get a chance. Request: https://github.com/RipMeApp/ripme/issues/38#issuecomment-326834354

**Comment by gitlerat** [comment]
Are there any news for sex.com? If it should work - it does not any more :)
kind regards

**Comment by raizudesuyo** [comment]
Is there somebody who is currently working on a tiktok ripper, I'm planning to work on it [comment](https://github.com/RipMeApp/ripme/issues/38#issuecomment-538817918)
